env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks
  - prettier
overrides:
  - env:
      jest: true
    files:
      - "**/*.test.js"
      - "**/*.test.jsx"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
root: true
rules:
  jsx-a11y/click-events-have-key-events: "off"
  react/function-component-definition: "off"
  react/jsx-filename-extension: "off"
  react/jsx-props-no-spreading: "off"
  react/prop-types: "off"
settings:
  react:
    version: detect
