jobs:
  schema:
    name: Check Schema
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check metadata field
        run: |
          for f in $(git ls-files "**/*.yml") 
          do
            a=`yq .Resources $f |jq '.|to_entries|.[]| if .value|[leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}]|from_entries|select([.[]]|.[]|test(".resolve."))|keys|map(select(.|contains("Metadata_WorkaroundSubSSM")))|any then empty else .key end'`
            if [[ -n "$a" ]]
            then
              echo "following resources need metadata field:"
              echo $a
              exit 1
            fi
          done
name: Check resources
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
