jobs:
  schema:
    name: Check resources metadata field
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          architecture: 'x64'
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install yq
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check metadata field
        run: |
          a=`git ls-files | grep -e '\.ya\?ml' | xargs -I  {} yq -S -Y . {}|jq '.|to_entries|.[]| if .value|[leaf_paths as $path | {"key": $path | join("_"), "value": getpath($path)}]|from_entries|select([.[]]|.[]|test(".resolve."))|keys|map(select(.|contains("Metadata_WorkaroundSubSSM")))|any then empty else .key end'`
          if [[ -n "$a" ]]
          then
            echo "following resources need metadata field:"
            echo $a
            exit 1
          fi
name: Check resources metadata
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
